version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    ports:
      - "3306:3306" # pc_port:container_port
    environment:
      - MYSQL_ROOT_PASSWORD=somesecretpassword
      - MYSQL_DATABASE=sw2cl2-db
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local
